org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

## gradle runs on jdk 21, newer is unsupported
## machine specific path
org.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64

## mod metadata
mod_id=magicmissiles
mod_name=Magic Missiles
mod_version=0.1.0
mod_group_id=net.washedupplayz.magicmissiles
mod_authors=washedupplayz
mod_description=A tech/military mod focused on launchable missiles with target tracking, radar, and missile interception.

## minecraft, neoforge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.242
neo_version_range=[21.1.0,)
loader_version_range=[4,)
